// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: StiMeter

#ifndef _STIMETER_UI_H
#define _STIMETER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * test_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( corvette_c5r_63_720);        // boot splash

// FONTS
// The dash uses the built-in Montserrat faces (enabled via sdkconfig) so the
// type matches the flat, modern look of the gauge design. The big centre RPM
// readout needs to be larger than the largest built-in (44), so it uses a
// generated digits-only Montserrat cut -- see fonts/ui_font_rpm_96.c.
LV_FONT_DECLARE( ui_font_rpm_96);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
